#acu user configurations
configurations:

  # load device configuration determined by tags (e.g. rock-5b)
  #device_config: generic-aarch64

  # do not confirm when installing a package using pacman -S / -U or makepkg -si
  #no_confirm: 1

  # do not print warning ($YELLOW) messages
  #no_warning: 1

  # do not clear terminal outputs
  #no_clear: 1

  # do not print warning ($YELLOW) messages
  #debug_log: 1

  # auto update acu when launch without asking
  #auto_update: 1

  # archive repo url for downgrading packages
  # Arch Linux ARM Archive repo
  alaa_url: https://alaa.ad24.cz

  # directory for storing source files
  source_repo_dir: .acu/sources

  # repo list
  repositories_file: .acu/config/repo.yaml
  repositories_url: https://raw.githubusercontent.com/kwankiu/acu/dev/example/tags.yaml

  # tags list
  tags_file: .acu/config/tags.yaml
  tags_url: https://raw.githubusercontent.com/kwankiu/acu/dev/example/tags.yaml

  # kernel list
  kernel_file: .acu/config/kernel.yaml
  kernel_url: https://raw.githubusercontent.com/kwankiu/acu/dev/example/kernel.yaml

  # bootloader list
  bootloader_file: .acu/config/bootloader.yaml
  bootloader_url: https://raw.githubusercontent.com/kwankiu/acu/dev/example/bootloader.yaml

  # apps list
  apps_file: .acu/config/apps.yaml
  apps_url: https://raw.githubusercontent.com/kwankiu/acu/dev/example/apps.yaml
