# List of available Linux Kernel options (with the required packages)

kernel:

## Example
#- package: linux-aarch64
#   description: Linux Mainline Kernel
#   version: 6.X
#   tags:
#     - generic-aarch64
#     - rpi
#   firmware:
#     - linux-firmware
#   graphics:
#     - mesa
#   video:
#     - ffmpeg

## More examples
# REPO USAGE:
#   repo:
#     - name: acu
#       type: acu
#       url: https://repo.example.org
#     - name: community
#       type: pacman
#       url: https://repo.example.org
#       gpg: ABC1234567890
# OTHERS USAGE:
#   others:
#     - rpi-imager
#     - neofetch
#     - chromium

  # Linux Mainline Kernel
  - package: linux-aarch64
    description: Linux Mainline Kernel
    version: 6.X
    tags:
      - generic-aarch64
      - rpi
    firmware:
      - linux-firmware
    graphics:
      - mesa
    video:
      - ffmpeg

  # Joshua Rockchip 5.10
  - package: linux-aarch64-rockchip-bsp5.10-joshua
    description: Linux Joshua Linux Rockchip Kernel
    version: 5.10.160
    tags:
      - rock5
      - edge2
      - orangepi5
      - zero3
    repo: 
      - name: 7Ji
    firmware:
      - linux-firmware-joshua-git
      - mali-valhall-g610-firmware
    graphics:
      - mesa-panfork-git
      - libmali-valhall-g610-x11-wayland-gbm
    video:
      - mpp-git
      - ffmpeg-mpp-git

  # Joshua Rockchip 6.1
  - package: linux-aarch64-rockchip-bsp6.1-joshua-git
    description: Linux Joshua Linux Rockchip Kernel
    version: 6.1.43
    tags:
      - rock5
      - edge2
      - orangepi5
      - zero3
    repo: 
      - name: 7Ji
    firmware:
      - linux-firmware-joshua-git
      - mali-valhall-g610-firmware
    graphics:
      - mesa-panfork-git
      - libmali-valhall-g610-x11-wayland-gbm
    video:
      - mpp-git
      - ffmpeg-mpp-git
