# List of devices tags (groups)
tags:

  # Generic tags
  generic-aarch64:
    - generic-aarch64

  # Rockchip tags
  rockchip:
    - rock-5a
    - rock-5b
    - zero-3w-wifi-4
    - zero-3w-wifi-6
    - zero-3e
    - edge2
    - orangepi-5
    - orangepi-5b
    - orangepi-5-plus

  rock5:
    - rock-5a
    - rock-5b

  orangepi5:
    - orangepi-5
    - orangepi-5b
    - orangepi-5-plus

  edge2:
    - edge2

  zero3:
    - zero-3w-wifi-4
    - zero-3w-wifi-6
    - zero-3e

  # Raspberry Pi tags
  rpi:
    - rpi-3
    - rpi-4
    - rpi-5
    - rpi-zero-2

  # Apple silicon tags (placeholder)
  apple:
    - apple-m1
